### ISSUE TITLE
django-health-check 3.3.0 SSL CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by AdrienLemaire** [codingjoe/django-health-check#179]
django-health-check v3.3.0 was working fine until I tried to reinstall it today. 
```
Collecting django-health-check==3.3.0 (from -r requirements.txt (line 5))
  Downloading django-health-check-3.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/pbr/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777) -- Some packages may not be found!
    Couldn't find index page for 'pbr' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777) -- Some packages may not be found!
    No local packages or working download links found for pbr
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lbv3uxiw/django-health-check/setup.py", line 6, in <module>
        pbr=True,
      File "/usr/local/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.6/site-packages/setuptools/dist.py", line 335, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python3.6/site-packages/setuptools/dist.py", line 456, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 863, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1141, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1153, in obtain
        return installer(requirement)
      File "/usr/local/lib/python3.6/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pbr')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lbv3uxiw/django-health-check/
```

**Comment by codingjoe** [comment]
As I understand it, PyPi's ssl certificate was not verified. That being said, they didn't change anything. They certificate they are using is from June 2017. I would recommend to check our local certificate store. Maybe you distrusted the root CA.
Anyway this has nothing to do with this package in particular.
Best
-Joe
