### ISSUE TITLE
Celery and RabbitMQ checks enabled concurrently results in errors

### ISSUE THREAD

**Issue by jbnance** [codingjoe/django-health-check#210]
Using:

- Python 3.6 and 3.7
- Django 2.1.4
- django-health-check 3.8.0
- celery 4.2.1
- RabbitMQ 3.3.5 and 3.6.16 (clustered)

With a fresh instance of RabbitMQ having both health checks enabled at the same time:

- health_check.contrib.celery
- health_check.contrib.rabbitmq

...results in celery workers erroring out with the following:

```[2019-01-11 13:32:06,428: CRITICAL/MainProcess] Unrecoverable error: TypeError("add() missing 2 required positional arguments: 'x' and 'y'",)
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/models/query.py", line 486, in get_or_create
    return self.get(**lookup), False
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
django_celery_results.models.TaskResult.DoesNotExist: TaskResult matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/worker/loops.py", line 88, in asynloop
    update_qos()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/common.py", line 417, in update
    return self.set(self.value)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/common.py", line 410, in set
    self.callback(prefetch_count=new_value)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/worker/consumer/tasks.py", line 47, in set_prefetch_count
    apply_global=qos_global,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/messaging.py", line 558, in qos
    apply_global)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/channel.py", line 1812, in basic_qos
    wait=spec.Basic.QosOk,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/abstract_channel.py", line 59, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/abstract_channel.py", line 79, in wait
    self.connection.drain_events(timeout=timeout)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/connection.py", line 491, in drain_events
    while not self.blocking_read(timeout):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/connection.py", line 497, in blocking_read
    return self.on_inbound_frame(frame)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/method_framing.py", line 77, in on_frame
    callback(channel, msg.frame_method, msg.frame_args, msg)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/connection.py", line 501, in on_inbound_method
    method_sig, payload, content,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/abstract_channel.py", line 128, in dispatch_method
    listener(*args)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/amqp/channel.py", line 1597, in _on_basic_deliver
    fun(msg)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/messaging.py", line 624, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 567, in on_task_received
    callbacks,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/worker/strategy.py", line 157, in task_message_handler
    if (req.expires or req.id in revoked_tasks) and req.revoked():
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/worker/request.py", line 280, in revoked
    'expired' if expired else 'revoked', False, None, expired,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/worker/request.py", line 263, in _announce_revoked
    self.id, reason, request=self, store_result=self.store_errors,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/backends/base.py", line 191, in mark_as_revoked
    traceback=None, request=request)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/backends/base.py", line 322, in store_result
    request=request, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django_celery_results/backends/database.py", line 35, in _store_result
    task_kwargs=task_kwargs,
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django_celery_results/managers.py", line 50, in _inner
    return fun(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django_celery_results/managers.py", line 126, in store_result
    obj, created = self.get_or_create(task_id=task_id, defaults=fields)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/models/query.py", line 488, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/models/query.py", line 521, in _create_object_from_params
    params = {k: v() if callable(v) else v for k, v in params.items()}
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/models/query.py", line 521, in <dictcomp>
    params = {k: v() if callable(v) else v for k, v in params.items()}
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/trace.py", line 642, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/celery/app/task.py", line 375, in __call__
    return self.run(*args, **kwargs)
TypeError: add() missing 2 required positional arguments: 'x' and 'y'
[2019-01-11 13:32:06,454: DEBUG/MainProcess] | Worker: Closing Hub...
[2019-01-11 13:32:06,455: DEBUG/MainProcess] | Worker: Closing Pool...
[2019-01-11 13:32:06,456: DEBUG/MainProcess] | Worker: Closing Consumer...
[2019-01-11 13:32:06,458: DEBUG/MainProcess] | Worker: Stopping Consumer...
[2019-01-11 13:32:06,459: DEBUG/MainProcess] | Consumer: Closing Connection...
[2019-01-11 13:32:06,460: DEBUG/MainProcess] | Consumer: Closing Events...
[2019-01-11 13:32:06,461: DEBUG/MainProcess] | Consumer: Closing Mingle...
[2019-01-11 13:32:06,463: DEBUG/MainProcess] | Consumer: Closing Gossip...
[2019-01-11 13:32:06,464: DEBUG/MainProcess] | Consumer: Closing Tasks...
[2019-01-11 13:32:06,465: DEBUG/MainProcess] | Consumer: Closing Control...
[2019-01-11 13:32:06,466: DEBUG/MainProcess] | Consumer: Closing Heart...
[2019-01-11 13:32:06,467: DEBUG/MainProcess] | Consumer: Closing event loop...
[2019-01-11 13:32:06,468: DEBUG/MainProcess] | Consumer: Stopping event loop...
[2019-01-11 13:32:06,469: DEBUG/MainProcess] | Consumer: Stopping Heart...
[2019-01-11 13:32:06,471: DEBUG/MainProcess] | Consumer: Stopping Control...
[2019-01-11 13:32:06,472: INFO/MainProcess] Received task: health_check.contrib.celery.tasks.add[c3d288cc-523d-4831-a788-35ba68375516]   expires:[2019-01-11 18:12:22.144025+00:00]
[2019-01-11 13:32:06,474: INFO/MainProcess] Discarding revoked task: health_check.contrib.celery.tasks.add[c3d288cc-523d-4831-a788-35ba68375516]
[2019-01-11 13:32:06,480: ERROR/MainProcess] Error on stopping Control: TypeError("add() missing 2 required positional arguments: 'x' and 'y'",)
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/models/query.py", line 486, in get_or_create
    return self.get(**lookup), False
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
django_celery_results.models.TaskResult.DoesNotExist: TaskResult matching query does not exist.

During handling of the above exception, another exception occurred:

...<snip>...```

If I disable either of the checks the other works just fine.

I was able to get both working concurrently by going through a few iterations of enabling one, then the other, then finally both at the same time so it seems that there's some sort of race condition.

**Comment by codingjoe** [comment]
I this error seems to be related to `django_celery_results` not health check. Why are you using it and not AMQP as a result backend for celery since you clearly have it installed?

**Comment by jbnance** [comment]
Oh, boy, I'm sorry for the noise.  The answer is, because I'm new at Celery and don't know what I'm doing.  :-(

I'll look into getting the results backend swapped over.

**Comment by jbnance** [comment]
Just to close the loop on my confusion - the reason I have/had `django_celery_results` deployed was for `celery_progress`.  I'm not sure if that's the right path and not asking for you to support other projects in your issue tracker - just trying to save face.  :-D

**Comment by codingjoe** [comment]
Sorry for the late response. Yes I think if you need help with celery, you should visit their GH page. I think they also have a IRC channel.
