### ISSUE TITLE
Support Redis Authentication

### ISSUE THREAD

**Issue by nniehoff** [codingjoe/django-health-check#279]
When checking the status of my redis environment I receive the following Exception:

```
Traceback (most recent call last):
   File "/usr/local/lib/python3.7/site-packages/health_check/contrib/redis/backends.py", line 25, in check_status
     conn.ping()  # exceptions may be raised upon ping
   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1378, in ping
     return self.execute_command('PING')
   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 901, in execute_command
     return self.parse_response(conn, command_name, **options)
   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 915, in parse_response
     response = connection.read_response()
   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 739, in read_response
     response = self._parser.read_response()
   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 340, in read_response
     raise error
 redis.exceptions.AuthenticationError: Authentication required.
```

This is a feature request to add the capability to authenticate to redis for health checks.

**Comment by codingjoe** [comment]
Hi @nniehoff,

Thanks for reaching out. Would you mind elaborating a bit more on what you are requesting? I am afraid I am not familiar with the exception you posted and to what authentication you refer.

Just a wild guess, does your Redis URL include any hostname or password as described here?
https://metacpan.org/pod/URI::redis

Best,
Joe

**Comment by nniehoff** [comment]
@codingjoe,

Thanks for getting back to me.  I am no redis expert by any means so I was just trying the redis URL from your documentation of `redis://redis:6379/0`.  Today, based on the link you provided I tried a more complete URL `redis://redis:6379/?db=0&password=secretpassword` and enabled debugging where I found this:

```
DEBUG Got redis://redis:6379/?db=0&password=secretpassword as the redis_url. Connecting to redis...
```

Still no luck.  Digging further I found some examples in the code for the `from_url` method in redis [here](https://github.com/andymccurdy/redis-py/blob/master/redis/connection.py#L1006).  Based on that I tried the `REDIS_URL` of `redis://:secretpassword@redis:6379/0` which worked!!  So I guess django-health-check supports authentication for redis you just have to build the correct URL which is obscurely documented to say the least in the redis code.

Thanks for the help, I'll let you decided if you want to update docs or just close this issue.

**Comment by codingjoe** [comment]
Hi @nniehoff,

You make a good point. I guess many people are used to the URL format, because of the whole [12factor](https://12factor.net/) idea to store credentials in the environment via URLs. It was originally promoted by Kenneth Reitz and Heroku  implemented in many PaaS providers too.

Feel free to open a patch to improve the documentation, though.

Best,
Joe

**Comment by twkrol** [comment]
By default, for the ease of accessing Redis from other containers via Docker networking, the "Protected mode" is turned off by default. This means there is no user:password settings to use in typical dockerized installation.
The app works fine, but the redis health check is unable to connect.
Any idea how to solve that?
