### ISSUE TITLE
Not compatible with explicit AppConfig

### ISSUE THREAD

**Issue by AstraLuma** [codingjoe/django-health-check#53]
If an [exact `AppConfig reference](https://docs.djangoproject.com/en/1.10/ref/applications/#for-application-users) is given in `INSTALLED_APPS` (instead of a package name), `django-health-check` fails with:

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\James\.virtualenvs\innocence-envs\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Users\James\.virtualenvs\innocence-envs\lib\site-packages\django\core\management\__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\James\.virtualenvs\innocence-envs\lib\site-packages\django\core\management\base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\James\.virtualenvs\innocence-envs\lib\site-packages\django\core\management\base.py", line 342, in execute
    self.check()
  File "C:\Users\James\.virtualenvs\innocence-envs\lib\site-packages\django\core\management\base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\James\.virtualenvs\innocence-envs\lib\site-packages\django\core\management\base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\James\.virtualenvs\innocence-envs\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\James\.virtualenvs\innocence-envs\lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\James\.virtualenvs\innocence-envs\lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "C:\Users\James\.virtualenvs\innocence-envs\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\James\.virtualenvs\innocence-envs\lib\site-packages\django\urls\resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\James\.virtualenvs\innocence-envs\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\James\.virtualenvs\innocence-envs\lib\site-packages\django\urls\resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\James\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\James\code\innocence-envs\innocence\urls.py", line 24, in <module>
    url(r'^health/', include('health_check.urls')),
  File "C:\Users\James\.virtualenvs\innocence-envs\lib\site-packages\django\conf\urls\__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\James\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\James\.virtualenvs\innocence-envs\lib\site-packages\health_check\urls.py", line 6, in <module>
    health_check.autodiscover()
  File "C:\Users\James\.virtualenvs\innocence-envs\lib\site-packages\health_check\__init__.py", line 25, in autodiscover
    mod = import_module(app)
  File "C:\Users\James\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ImportError: No module named 'django.contrib.admin.apps.SimpleAdminConfig'; 'django.contrib.admin.apps' is not a package
```

**Comment by ananthb** [comment]
I've run unto the exact same issue. Changed it up by using default_app_config in __init__.py, but I would love a fix for this. Is the issue stemming from using settings.INSTALLED_APPS instead of django.apps.apps here: https://github.com/KristianOellegaard/django-health-check/blob/master/health_check/__init__.py#L24

**Comment by AstraLuma** [comment]
@ananthb My problem is that it's with `django.contrib.admin`, so I can't just change the `default_app_config`.
