### ISSUE TITLE
DB migrations fail when upgrading to v1.2.0

### ISSUE THREAD

**Issue by christopherdcunha** [codingjoe/django-health-check#61]
# Tested with

- django 1.8.15
- django-health-check 1.1.4 migrated to 1.2.0

# Steps to reproduce
[Install django 1.8.15 and django-health-check 1.1.4](#given1)
[Configure django-health-check](#given2)
[Migrate the database](#given3)
[Upgrade to django-health-check 1.2.0](#when1)
[Migrate the database and see that the migration fails](#then)

# Work arounds
[Fake the database migration](#workaround)

<a name="given1"/>

## Install django 1.8.15 and django-health-check 1.1.4

```bash
$ mktmpenv     
$ pip install django==1.8.15 django-health-check==1.1.4 
$ pip freeze
Django==1.8.15
django-health-check==1.1.4
```

<a name="given2"/>

## Configure django-health-check

```bash
$ django-admin startproject myproject                  
$ vim ./myproject/myproject/settings.py 
# Add 'health_check_*' to INSTALLED_APPS
$ vim ./myproject/myproject/urls.py
# Add '/healthcheck/' URLs.
```

<a name="given3"/>

## Migrate the database

```bash
$ ./myproject/manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: health_check, staticfiles, messages, health_check_storage, health_check_db, health_check_cache
  Apply all migrations: admin, contenttypes, auth, sessions
Synchronizing apps without migrations:
  Creating tables...
    Creating table health_check_db_testmodel
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying sessions.0001_initial... OK
```
  
<a name="when1"/>

## Upgrade to django-health-check 1.2.0

```bash
$ pip install django==1.8.15 django-health-check==1.2.0
```

<a name="then"/>

## Migrate the database and see that the migration fails

```
$ ./myproject/manage.py migrate                        
Operations to perform:
  Synchronize unmigrated apps: staticfiles, health_check, messages, health_check_storage, health_check_cache
  Apply all migrations: admin, contenttypes, health_check_db, auth, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying health_check_db.0001_initial...Traceback (most recent call last):
  File "./myproject/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/christopherd/.virtualenvs/tmp-1bfff73823f1c428/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/christopherd/.virtualenvs/tmp-1bfff73823f1c428/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/christopherd/.virtualenvs/tmp-1bfff73823f1c428/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/christopherd/.virtualenvs/tmp-1bfff73823f1c428/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/christopherd/.virtualenvs/tmp-1bfff73823f1c428/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/christopherd/.virtualenvs/tmp-1bfff73823f1c428/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/christopherd/.virtualenvs/tmp-1bfff73823f1c428/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/christopherd/.virtualenvs/tmp-1bfff73823f1c428/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/christopherd/.virtualenvs/tmp-1bfff73823f1c428/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/home/christopherd/.virtualenvs/tmp-1bfff73823f1c428/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/home/christopherd/.virtualenvs/tmp-1bfff73823f1c428/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/home/christopherd/.virtualenvs/tmp-1bfff73823f1c428/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/christopherd/.virtualenvs/tmp-1bfff73823f1c428/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/christopherd/.virtualenvs/tmp-1bfff73823f1c428/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/christopherd/.virtualenvs/tmp-1bfff73823f1c428/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/home/christopherd/.virtualenvs/tmp-1bfff73823f1c428/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 316, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: table "health_check_db_testmodel" already exists
```

<a name="workaround"/>

## Fake the database migration

```bash
$ ./myproject/manage.py migrate --list
admin
 [X] 0001_initial
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
health_check_db
 [ ] 0001_initial
sessions
 [X] 0001_initial
$ ./myproject/manage.py migrate health_check_db 0001 --fake
Operations to perform:
  Target specific migration: 0001_initial, from health_check_db
Running migrations:
  Rendering model states... DONE
  Applying health_check_db.0001_initial... FAKED
$ ./myproject/manage.py runserver  
Performing system checks...

System check identified no issues (0 silenced).
November 21, 2016 - 15:37:25
Django version 1.8.15, using settings 'myproject.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[21/Nov/2016 15:37:26] "GET /healthcheck HTTP/1.1" 301 0
[21/Nov/2016 15:37:26] "GET /healthcheck/ HTTP/1.1" 200 1516
```

**Comment by codingjoe** [comment]
@christopherdcunha seems to be valid. I don't know what happened in those versions tho. I don't think there is any way to fix this, since both versions are released and I can't chance the past.

I will leave this ticket, so people will know how to work around the issue, should they bump into it too.

Thanks!
