### ISSUE TITLE
Installation steps

### ISSUE THREAD

**Issue by morenoh149** [codingjoe/django-health-check#77]
My django project may be nonstandard hence my troubles.

I have made the following changes

```python
# projectName/core/foo/internal/views.py
+import health_check.backends.base

fooViewSet(projectName.common.internal.views.ModelViewSet):
             instance.fail()
             instance.save()
         return self.instance_to_json(request, instance)
+
+class CustomTest(health_check.backends.base.BaseHealthCheckBackend):
+    def check_status(self):
+        try:
+            my_model = projectName.core.foo.models.Foo.objects.create(
+                source=projectName.core.foo.models.Foo.CONST,
+            )
+            my_model.save()
+            my_model.delete()
+            return True
+        except IntegrityError:
+            raise ServiceReturnedUnexpectedResult("Integrity Error")
+        except DatabaseError:
+            raise ServiceUnavailable("Database error")
+
+django.contrib.admin.site.register(CustomTest)
```

```python
# projectName/core/urls.py
 import django.conf.urls
 
+import health_check

...

 internal_urls = [
+    django.conf.urls.url(r'^ht/', django.conf.urls.include(health_check.urls)),
 ]

urlpatterns = [
    django.conf.urls.url(r'^internal/', django.conf.urls.include(internal_urls, namespace='core_internal')),
]
```

```python
# /config/settings/__default__.py b/config/settings/__default__.py
INSTALLED_APPS = [
+    'health_check',
+    'health_check_celery3',
+    'health_check_db',
+    'health_check_cache',
+    'health_check_storage',
]
```

```txt
# requirements.txt
+django-health-check==1.3.0
```

I get the error
```bash
Traceback (most recent call last):
          File "manage.py", line 17, in <module>
              execute_from_command_line(sys.argv)
            File "/Users/harry/programming/project/env/project/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
              utility.execute()
            File "/Users/harry/programming/project/env/project/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
              self.fetch_command(subcommand).run_from_argv(self.argv)
            File "/Users/harry/programming/project/env/project/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
              self.execute(*args, **cmd_options)
            File "/Users/harry/programming/project/env/project/lib/python2.7/site-packages/django/core/management/base.py", line 398, in execute
              self.check()
            File "/Users/harry/programming/project/env/project/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
              include_deployment_checks=include_deployment_checks,
                File "/Users/harry/programming/project/env/project/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
              new_errors = check(app_configs=app_configs)
            File "/Users/harry/programming/project/env/project/lib/python2.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
              return check_resolver(resolver)
            File "/Users/harry/programming/project/env/project/lib/python2.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
              for pattern in resolver.url_patterns:
            File "/Users/harry/programming/project/env/project/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
              res = instance.__dict__[self.name] = self.func(instance)
            File "/Users/harry/programming/project/env/project/lib/python2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
              patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
            File "/Users/harry/programming/project/env/project/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
              res = instance.__dict__[self.name] = self.func(instance)
            File "/Users/harry/programming/project/env/project/lib/python2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
              return import_module(self.urlconf_name)
            File "/opt/foo/.pyenv/versions/2.7.11/lib/python2.7/importlib/__init__.py", line 37, in import_module
              __import__(name)
            File "/Users/harry/programming/project/foo/urls.py", line 7, in <module>
              import foo.core.urls
            File "/Users/harry/programming/project/foo/core/urls.py", line 13, in <module>
              import foo.core.modelName.internal.views
            File "/Users/harry/programming/project/foo/core/modelName/internal/views.py", line 176, in <module>
              django.contrib.admin.site.register(HealthCheckModelLookup)
            File "/Users/harry/programming/project/env/project/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 86, in register
              for model in model_or_iterable:
          TypeError: 'type' object is not iterable
```

**Comment by codingjoe** [comment]
@morenoh149 you did register it to the django admin ;) Does that solve your issue?

**Comment by morenoh149** [comment]
this line?
`+django.contrib.admin.site.register(CustomTest)`

How does one register a package in the django admin?

**Comment by aleksihakli** [comment]
You are not supposed to register the package to the admin site but the health check plugin directory. Try removing the admin registration and see how the built in modules register. Make sure to look in the master branch.

**Comment by codingjoe** [comment]
@morenoh149 `health_check.plugins.plugin_dir.register()`
